//AUTOGENERATED
using UnityEngine;
using UnityEngine.UIElements;
using UnityEditor;
using UnityEditor.UIElements;

public partial class SampleWindow
{
    protected override string TreeAssetPath => "Assets/Samples/Editor/SampleWindow.uxml";
    protected override void RegisterCallbacks()
    {
        rootVisualElement.Q<Button>("button2").clicked += OnClick_button2;
    }
}
